### ISSUE TITLE
Activity not working

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/tamtam#4]
on running ```sugar-activity .``` the following error is thrown:
```
Guessing python class from activity.info!
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 220, in <module>
    main()
  File "/usr/bin/sugar-activity", line 164, in main
    module = __import__(module_name)
ImportError: No module named TamTamSuite
```

Also a few files are ported to Gtk3 and some are not, not sure if the porting is complete on in progress in any fork. @quozl what do you think?

**Comment by quozl** [comment]
It would be best to work on the import failure first.  Most likely it is because Tam Tam is a multiple activity source repository and you are trying to start it from a git clone instead of building and installing the bundles first.  Using `sugar-activity` in a git clone only works for simply structured activities.

We have Tam Tam bundles for OLPC OS on Fedora 18 at https://download.laptop.org/activities but we don't use them for OLPC OS on Ubuntu 16.04, and don't plan to use them on Ubuntu 18.04.  So TamTam isn't a priority for me personally.

https://github.com/sugarlabs/music-keyboard-activity is a port to GTK+ 3, and Csound 6.x, and has within some source that was once from Tam Tam.  The 32-bit binaries will also give you pause.

Huge job, best of luck!  :grin:
